[tool.poetry]
name = "gtfs-go"
version = "0.1.0"
description = ""
authors = ["Kanahiro <mediterranean1769@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
ruff = "^0.0.274"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
pytest = "^7.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["F", "E", "W", "B", "C90", "N", "I"]
ignore = ["N802", "E501"]
target-version = "py37"