import math

from qgis.core import (
    QgsFeature,
    QgsFeatureSink,
    QgsField,
    QgsFields,
    QgsGeometry,
    QgsPointXY,
    QgsProcessingFeedback,
)
from qgis.PyQt.QtCore import QMetaType

# Tweeked to import gtfs_parser for Python 3.11
try:
    from gtfs_parser import gtfs_parser
except ImportError:
    # Python 3.9 or 3.10
    import gtfs_parser

GTFS_FILE_FILTER = "GTFS (*.zip *.ZIP)"


def make_fields(definitions: list) -> QgsFields:
    """
    Args:
        definitions: list of (name, QMetaType.Type)
    """
    fields = QgsFields()
    for name, field_type in definitions:
        if field_type == QMetaType.Type.QStringList:
            fields.append(QgsField(name, field_type, subType=QMetaType.Type.QString))
        else:
            fields.append(QgsField(name, field_type))
    return fields


def _to_attribute(value):
    # pandas yields NaN for missing values
    if isinstance(value, float) and math.isnan(value):
        return None
    if isinstance(value, (list, tuple)):
        return [str(v) for v in value]
    if hasattr(value, "item"):
        # numpy scalar
        return value.item()
    return value


def _to_geometry(geometry: dict) -> QgsGeometry:
    geom_type = geometry["type"]
    coords = geometry["coordinates"]
    if geom_type == "Point":
        return QgsGeometry.fromPointXY(QgsPointXY(coords[0], coords[1]))
    if geom_type == "LineString":
        return QgsGeometry.fromPolylineXY([QgsPointXY(x, y) for x, y in coords])
    if geom_type == "MultiLineString":
        return QgsGeometry.fromMultiPolylineXY(
            [[QgsPointXY(x, y) for x, y in line] for line in coords]
        )
    raise ValueError(f"unsupported geometry type: {geom_type}")


def write_features(
    sink: QgsFeatureSink,
    fields: QgsFields,
    features: list,
    feedback: QgsProcessingFeedback,
) -> None:
    """
    Write GeoJSON-Feature-like dicts (or plain dicts as attribute-only records)
    generated by gtfs_parser into a sink.
    """
    total = len(features)
    for i, src in enumerate(features):
        if feedback.isCanceled():
            break
        properties = src.get("properties", src)
        feature = QgsFeature(fields)
        if "geometry" in src:
            feature.setGeometry(_to_geometry(src["geometry"]))
        feature.setAttributes(
            [_to_attribute(properties.get(name)) for name in fields.names()]
        )
        sink.addFeature(feature, QgsFeatureSink.Flag.FastInsert)
        if total:
            feedback.setProgress(100 * (i + 1) / total)
