name: Test plugin

on:
    pull_request:
        branches:
            - main

env:
    # plugin name/directory where the code for the plugin is stored
    PLUGIN_NAME: gtfsgo
    # python notation to test running inside plugin
    TESTS_RUN_FUNCTION: gtfsgo.test_suite.test_package
    # Docker settings
    DOCKER_IMAGE: qgis/qgis

jobs:
    Test-plugin-felt:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                docker_tags: [release-3_28]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Export requirements.txt
              run: |
                  pip3 install poetry
                  poetry export --with dev -f requirements.txt -o requirements.txt

            - name: Docker pull and create qgis-testing-environment
              run: |
                  docker pull "$DOCKER_IMAGE":${{ matrix.docker_tags }}
                  docker run -d --name qgis-testing-environment -v "$GITHUB_WORKSPACE":/tests_directory/gtfsgo -e DISPLAY=:99 "$DOCKER_IMAGE":${{ matrix.docker_tags }}

            - name: Docker set up QGIS
              run: |
                  docker exec qgis-testing-environment sh -c "qgis_setup.sh $PLUGIN_NAME"
                  docker exec qgis-testing-environment sh -c "rm -f /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/$PLUGIN_NAME"
                  docker exec qgis-testing-environment sh -c "ln -s /tests_directory/$PLUGIN_NAME /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/$PLUGIN_NAME"
                  docker exec qgis-testing-environment sh -c "pip3 install -r gtfsgo/requirements.txt"

            - name: Docker run plugin tests
              run: |
                  docker exec qgis-testing-environment sh -c "qgis_testrunner.sh $TESTS_RUN_FUNCTION"
